//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class donacija
    {
        public donacija()
        {
            this.test = new HashSet<test>();
            this.transfuzija = new HashSet<transfuzija>();
        }
    
        public int donacijaID { get; set; }
        public System.DateTime vrijeme { get; set; }
        public string napomena { get; set; }
        public Nullable<int> kolicina { get; set; }
        public int donacija_pacijentID { get; set; }
        public int donacija_hladnjakID { get; set; }
        public int donacija_zaposlenikID { get; set; }
    
        public virtual hladnjak hladnjak { get; set; }
        public virtual pacijent pacijent { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
        public virtual ICollection<test> test { get; set; }
        public virtual ICollection<transfuzija> transfuzija { get; set; }
    }
}
