//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class hladnjak
    {
        public hladnjak()
        {
            this.donacija = new HashSet<donacija>();
        }
    
        public int hladnjakID { get; set; }
        public string naziv { get; set; }
        public Nullable<bool> pun { get; set; }
        public int hladnjak_krvnaGrupaID { get; set; }
    
        public virtual ICollection<donacija> donacija { get; set; }
        public virtual krvnagrupa krvnagrupa { get; set; }
    }
}
