//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacijent
    {
        public pacijent()
        {
            this.donacija = new HashSet<donacija>();
            this.transfuzija = new HashSet<transfuzija>();
        }
    
        public int pacijentID { get; set; }
        public string OIB { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa { get; set; }
        public string brojPoliceOsiguranja { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string tezina { get; set; }
        public Nullable<System.DateTime> datum_rodenja { get; set; }
        public int pacijent_krvnaGrupaID { get; set; }
        public int pacijent_tipPacijentaID { get; set; }
        public int pacijent_spolID { get; set; }
    
        public virtual ICollection<donacija> donacija { get; set; }
        public virtual krvnagrupa krvnagrupa { get; set; }
        public virtual spol spol { get; set; }
        public virtual tippacijenta tippacijenta { get; set; }
        public virtual ICollection<transfuzija> transfuzija { get; set; }
    }
}
