//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class spol
    {
        public spol()
        {
            this.pacijent = new HashSet<pacijent>();
        }
    
        public int spolID { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<pacijent> pacijent { get; set; }
    }
}
