//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int testID { get; set; }
        public bool odobren { get; set; }
        public System.DateTime vrijeme { get; set; }
        public int test_ustanovaID { get; set; }
        public int test_bolestID { get; set; }
        public int test_donacijaID { get; set; }
    
        public virtual bolest bolest { get; set; }
        public virtual donacija donacija { get; set; }
        public virtual ustanova ustanova { get; set; }
    }
}
