//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipptreakcije
    {
        public tipptreakcije()
        {
            this.transfuzija = new HashSet<transfuzija>();
        }
    
        public int tipPtReakcijeID { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<transfuzija> transfuzija { get; set; }
    }
}
