//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ustanova
    {
        public ustanova()
        {
            this.test = new HashSet<test>();
            this.transfuzija = new HashSet<transfuzija>();
            this.zaposlenik = new HashSet<zaposlenik>();
        }
    
        public int ustanovaID { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
    
        public virtual ICollection<test> test { get; set; }
        public virtual ICollection<transfuzija> transfuzija { get; set; }
        public virtual ICollection<zaposlenik> zaposlenik { get; set; }
    }
}
