//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaKrvi
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenik
    {
        public zaposlenik()
        {
            this.donacija = new HashSet<donacija>();
        }
    
        public int zaposlenikID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public int zaposlenik_tipZaposlenikaID { get; set; }
        public int zaposlenik_ustanovaID { get; set; }
    
        public virtual ICollection<donacija> donacija { get; set; }
        public virtual tipzaposlenika tipzaposlenika { get; set; }
        public virtual ustanova ustanova { get; set; }
    }
}
